09
js-tasks-ru/vue-20230905_zvezdinvladislav pull request #10
Opened 2023-10-14 12:28 UTC by Vlad-95

Не очень понял, почему в 09/01 не проходило проверку на "Не массив". Я добавил проверку на массив, тесты прошел, но я все равно не понимаю, мы ведь в пропсах указываем тип [Object, Array], но все равно пришлось писать проверку в самом рендере.

2023-10-14 12:30 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-15 15:14 UTC, ShGKme requested changes

2023-10-15 15:14 UTC, ShGKme commented on 09-rendering/01-VNode/components/VNode.vue
> +  },
Здесь на основе уже существующего узла `vnode` создаётся новый узел. При этом из старого узла передаются только тип, параметры и дети, но теряется всё остальное: инкапсуляция стилей, оптимизации, и даже такие вещи, как ref, ключ.

Полностью склонировать `vnode` можно с помощью функции `cloneVNode`. Но здесь не требуется их клонировать.

`render` функция - возвращает `vnode`. `vnode` уже есть, её/их достаточно просто вернуть и всё

2023-10-18 09:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-19 14:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-21 12:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-24 10:58 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-24 11:00 UTC, Vlad-95 commented
Почему-то тесты не проходили на самом гитхабе, хотя локально у меня все было ок. Пришлось в некоторых задачах нажимать кнопку для получения вашего решения, зато теперь проверки прошли))

2023-10-24 14:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-24 22:45 UTC, ShGKme commented on 09-rendering/03-UiPanes-JSX/components/UiPanes.vue
> +      panes: [0, 1, 2, 3],
В этом решении фиксировано 4 элемента, но может быть любое количество

2023-10-24 22:45 UTC, ShGKme commented on 09-rendering/03-UiPanes-JSX/components/UiPanes.vue
> +    },
Все элементы передаются в одном слоте - слоте по умолчанию

2023-10-24 22:45 UTC, ShGKme commented on 09-rendering/03-UiPanes-JSX/components/UiPanes.vue
> +    },
Решение, когда каждый элемент нужно было оборачивать в `<template v-slot:item-X` - работало и без рендер функции. Но это была проблема - требовалось оборачивать всё в отдельные слоты.

Цель перевода компонента на рендер функцию - избавиться от оборачивания каждого узла в слот.

2023-10-24 22:45 UTC, ShGKme approved these changes

2023-10-24 22:46 UTC, merged